### ISSUE TITLE
Compilation failed for package ‘vcfR’

### ISSUE THREAD

**Issue by FannyPouyet** [knausb/vcfR#156]
Hello,

vcfR looks perfect for me as I want to  estimate the ploidy of samples from a VCF. So I decided to give it a try but I didn't manage to install it, maybe because of some ambiguity in gt_to_popsum function? 

My session infos are:
R version 3.5.1 (2018-07-02)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS release 6.5 (Final)

Matrix products: default
BLAS: /usr/lib64/R/lib/libRblas.so
LAPACK: /usr/lib64/R/lib/libRlapack.so

>install.packages("vcfR")
Secure CRAN mirrors 
essai de l'URL 'https://pbil.univ-lyon1.fr/CRAN/src/contrib/vcfR_1.10.0.tar.gz'
Content type 'application/x-gzip' length 1453006 bytes (1.4 MB)
==================================================
downloaded 1.4 MB

* installing *source* package ‘vcfR’ ...
** package ‘vcfR’ correctement décompressé et sommes MD5 vérifiées
** libs
g++ -m64 -std=gnu++0x -I"/usr/include/R" -DNDEBUG  -I"/home/p/R/x86_64-redhat-linux-gnu-library/3.5/Rcpp/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c NM2winNM.cpp -o NM2winNM.o
g++ -m64 -std=gnu++0x -I"/usr/include/R" -DNDEBUG  -I"/home/p/R/x86_64-redhat-linux-gnu-library/3.5/Rcpp/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c RcppExports.cpp -o RcppExports.o
g++ -m64 -std=gnu++0x -I"/usr/include/R" -DNDEBUG  -I"/home/p/R/x86_64-redhat-linux-gnu-library/3.5/Rcpp/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c ad_frequency.cpp -o ad_frequency.o
g++ -m64 -std=gnu++0x -I"/usr/include/R" -DNDEBUG  -I"/home/p/R/x86_64-redhat-linux-gnu-library/3.5/Rcpp/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c deprecated_funcs.cpp -o deprecated_funcs.o
g++ -m64 -std=gnu++0x -I"/usr/include/R" -DNDEBUG  -I"/home/p/R/x86_64-redhat-linux-gnu-library/3.5/Rcpp/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c extract_gt.cpp -o extract_gt.o
g++ -m64 -std=gnu++0x -I"/usr/include/R" -DNDEBUG  -I"/home/p/R/x86_64-redhat-linux-gnu-library/3.5/Rcpp/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c freq_peak.cpp -o freq_peak.o
g++ -m64 -std=gnu++0x -I"/usr/include/R" -DNDEBUG  -I"/home/p/R/x86_64-redhat-linux-gnu-library/3.5/Rcpp/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c gt_to_popsum.cpp -o gt_to_popsum.o
gt_to_popsum.cpp: In function ‘Rcpp::DataFrame gt_to_popsum(Rcpp::DataFrame, Rcpp::CharacterMatrix)’:
gt_to_popsum.cpp:103: erreur: call of overloaded ‘to_string(int&)’ is ambiguous
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2604: note: candidats sont: std::string std::to_string(long long int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2610: note:                 std::string std::to_string(long long unsigned int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2616: note:                 std::string std::to_string(long double)
gt_to_popsum.cpp:106: erreur: call of overloaded ‘to_string(int&)’ is ambiguous
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2604: note: candidats sont: std::string std::to_string(long long int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2610: note:                 std::string std::to_string(long long unsigned int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2616: note:                 std::string std::to_string(long double)
make: *** [gt_to_popsum.o] Erreur 1
ERROR: compilation failed for package ‘vcfR’

Warning message:
In install.packages("vcfR") :
  l'installation du package ‘vcfR’ a eu un statut de sortie non nul

Thanks in advance for your help
Fanny
PS: my system is in french, sorry about that!

**Comment by knausb** [comment]
Bonjour! (Several years of French class and that's about as far as I can remember, so sorry from me.) I'm going to say that this does not sound like a vcfR issue. Let's walk through why I think that. When someone tells me their installation failed one of the first things I check is the [CRAN check results](https://cran.r-project.org/web/checks/check_results_vcfR.html). We see that we are building and testing successfully on several flavors of Linux. But not CentOS. Our HPC is running CentOS (actually, I believe it's RedHat Enterprise,  but this is what I get).

```
$ rpm -q centos-release
centos-release-7-7.1908.0.el7.centos.x86_64
centos-release-7-2.1511.el7.centos.2.10.x86_64
```

Which is not the version you're using. But I am able to successfully install there, so it's sounding like this may be specific to your machine. I next try Google.

```
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2616: note: std::string std::to_string(long double) make:
```

This is your error message with the vcfR specific parts removed. We get a lot of hits to GitHub pages which tells me you're not alone, that's usually good. The following post:

```
https://github.com/suhrig/arriba/issues/3
```

tells us what I think your issue is. CentOS 6 appears to to use an older compiler that does not include "overloaded function of to_string() for the float data type".  Back at my HPC I see the following.

```
$ gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)
```

I'm going to guess that your gcc is an older version, maybe even major release 3. If I'm correct, we have a few options.

If you have admin priviledges on this machine I'd suggest you try to update your gcc. I'm going to guess that your version of CentOS may not upgrade to a recent enough version of gcc. But this seems relatively easy so might as well try it.

Another option may be to upgrade your CentOS. CentOS 7 appears to have a gcc with the functionality that vcfR is looking for. And it appears that CentOS is on version 8 now. Upgrading your OS to use one package is pretty drastic. But you may encounter similar issues with other software.

Another option is to tell R to use a different version of gcc when compiling. It may be that your system has multiple versions of gcc already.

```
$ which gcc
```

Should let you know what's installed. I'm going guess you'll need at least gcc version 4. You'll than need to modify you `~/.R/Makevars` file. Google founf the following SO post.

```
https://stackoverflow.com/questions/1616983/building-r-packages-using-alternate-gcc
```

If that version doesn't "speak to you" you may be able to find other flavors online. Honestly, this last option sounds like the best option if you want to preserve your system as it is. But it also sounds like the most complicated answer. You'll have to decide for yourself what fits your needs.

Please let me know if any of this helps. Merci!

**Comment by jan-glx** [comment]
Wow, did not expect to find such a gem here! Great explanation how to solve such a problem (not mine)

**Comment by FannyPouyet** [comment]
Sorry for the delay in my response. It helped a lot, I ended up updating
the gcc version and now it works. Thank you for this detailed and quick
response.

Le lun. 8 juin 2020 à 23:25, Jan Gleixner <notifications@github.com> a
écrit :
