### ISSUE TITLE
summary() for vcfR

### ISSUE THREAD

**Issue by knausb** [knausb/vcfR#16]
A summary function for objects of class vcfR would provide feedback on what was read in to R. It could include:

- Sample number
- Variant number
- Percent NA
- Number of chromosomes

See genlight or DNAbin for examples.

**Comment by zkamvar** [comment]
[The genlight objects utilize the "show" method](https://github.com/thibautjombart/adegenet/blob/master/R/basicMethods.R#L237-L314) for summaries since it's a generic function. 

If you want to keep your show method, it shouldn't be too difficult to set summary as generic and then declare it as a method to vcfR.

**Comment by knausb** [comment]
Thank you for the example! That helps a lot.  I think my current show method is very similar to the head method.  So I think I can just rewrite the show method. I'll keep this open, with your link, until I do.

**Comment by zkamvar** [comment]
Additionally, if it pleases you, [here's my definition of the "show" method for genclone](https://github.com/grunwaldlab/poppr/blob/de9b50e6e9f23109b4c1065f42d23d8172186d6b/R/methods.r#L555-L618).

**Comment by knausb** [comment]
Simplified the show method for objects of class vcfR.
