### ISSUE TITLE
Annotation challenges

### ISSUE THREAD

**Issue by mlpimsler** [knausb/vcfR#24]
Hi- thanks for making this package available.  I am really excited about all of the features.

I am working with a non-model organism, though I have .gff and .vcf files.  I am working with SNP's from RNA-seq work, and therefore SNPs aren't called in all of the areas which have annotations.  I was trying to create a chomR object, but received the following message:

> Annotation positions exceed chromosome positions.  Is this the correct set of annotations?

I checked both the .vcf file and the .gff file and there aren't any annotations or SNP's called in a position that doesn't exist in the files. I tried this with a few other files as well and got the same message.  Any assistance would be greatly appreciated.  I have included two example files.

[example.zip](https://github.com/knausb/vcfR/files/163977/example.zip)

**Comment by knausb** [comment]
Hello, you appear to have done something I have never tried. And I think we'll have to call it a bug. You do not appear to be using a sequence (FASTA file). This means my code doesn't have a reliable way to determine the length of your chromosome. My code tries to make a guess by selecting the greatest value from the VCF file. You have an annotation beyond the greatest position in your VCF and this throws the error you've reported. At this point I think we have several options.

1) You could use your reference. You used this to to call variants, so you must have something. This will allow the code to git the chromosome length from this sequence.

2) You can omit the offending annotations. Something like:

    vcf <- read.vcfR('example.vcf')
    len <- max(as.numeric(as.character(vcf@fix[,'POS'])))
    gff <- read.table("example.gff", sep='\t', quote='')
    gff2 <- gff[gff[,4] <= len,]
    gff2 <- gff2[gff2[,5] <= len,]

This would remove some of your annotations, so its suboptimal. But it works.

3) You could try the devel branch from GitHub, if you're into that sort of thing. I've used your example to engineer my function so that it can handle this sort of thing. It will eventually end up on CRAN. But as of today is only at GitHub. Thank you for helping me improve vcfR!

I hope that helps!
