### ISSUE TITLE
Error with output of vcf.write()

### ISSUE THREAD

**Issue by AbigailShockey** [knausb/vcfR#25]
Hi,

I've been running through the vignettes outlined on the CRAN repository with both my own data and the example data from pinfsc50. I noticed that vcf.write() does not appear to be writing a vcf that excludes low quality variants (identified by masker()) when mask = TRUE. The only difference between the new and original vcf I can discern are entries in the FILTER column (which all say PASS). Am I misunderstanding what the output of write.vcf() is when mask = TRUE? Or is this an error? This is the code I've been using: 

library(vcfR)

vcf_file <- system.file("extdata", "pinf_sc50.vcf.gz", package = "pinfsc50")
dna_file <- system.file("extdata", "pinf_sc50.fasta", package = "pinfsc50")
gff_file <- system.file("extdata", "pinf_sc50.gff", package = "pinfsc50")

vcf <- read.vcfR(vcf_file, verbose = FALSE)
dna <- ape::read.dna(dna_file, format = "fasta")
gff <- read.table(gff_file, sep="\t", quote="")

chrom <- create.chromR(name="Supercontig", vcf=vcf, seq=dna, ann=gff, verbose=FALSE)
chrom <- proc.chromR(chrom, verbose = TRUE)

chrom <- masker(chrom, min_QUAL=0, min_DP=350, max_DP=650, min_MQ=59.5, max_MQ=60.5)
chrom <- proc.chromR(chrom, verbose = FALSE)

write.vcf(chrom, file="good_variants.vcf.gz", mask=TRUE)

Any help on this would be greatly appreciated

**Comment by knausb** [comment]
Hi Abigail,

You've discovered a bug. The behavior you expect is what I had expected. I have tried to fix this and have updated the devel branch. I've also used this information to create a unit test so that when the project gets built in the future this behavior will be tested. If you're interested, you could try to install the devel branch to see if I have resolved your issue. If you're not interested in trying the devel branch the following may help.

    chrom@vcf <- chrom@vcf[chrom@var.info$mask,]

If you put this line immediately before the `write.vcf` statement it should subset your object to only the data that has not been masked.

Good luck and I hope that helps!

**Comment by AbigailShockey** [comment]
Hi Brian,

This line of code worked like a charm. vcfR has been a great tool for exploring my data. Thank you for your help in resolving this!
