### ISSUE TITLE
Error: File does not appear to exist!

### ISSUE THREAD

**Issue by lauscherin** [knausb/vcfR#27]
Dear developer of the vcfR package,

I like to work with this package and will use it to implement into a Shinyapp.
But unfortunately, at different PCs and Laptops, read.vcfR doesn't work.
First, I thought it has to do with the operating system, but even on some Macs it doesn't work.
It always tells me that the File does not appear to exist... what could be the reason? Especially, because it works on some PCs/Laptops?!

Many thanks in advance,
Angela

**Comment by knausb** [comment]
Hi Angela,

I'm afraid I don't feel I have enough information to help you on this. Could you provide a minimal working example that reproduces the issue? This would help me trouble shoot this matter. Unit tests were run on Linux, Mac and Windows prior to submission to CRAN, so I can validate that I can get this to run on all of these platforms.

There is a known issue with tilde expansion. In order to open gzipped VCF files I've used zlib which does not appear to perform tilde expansion. Are the files you're trying to open in your working directory? This should be addressed in the GitHub versions (both master and devel). If you are inclined you could try the GitHub version to see if this resolves your issue. You'll need a compiler though. Mac can get this through Xcode and Windows with Rtools.

If you can provide me with an example that reproduces the issue I'll try to work on it. Thanks for your interest in vcfR!
Brian

**Comment by lauscherin** [comment]
Hi,

I could figure out that this problem has to due with writing permissions of R and not with your tool. I'm sorry for that question!

But many thanks!
Angela

**Comment by knausb** [comment]
No worries! Glad to hear things are working for you now.

**Comment by pa279** [comment]
Dear Angela!

How did you solve the problem as I am facing the same issue?

Thanks,

Agre
