### ISSUE TITLE
extract_info_tidy(info_types = TRUE) as default

### ISSUE THREAD

**Issue by knausb** [knausb/vcfR#44]
The function `extract_info_tidy()` currently has a default setting of `info_types = NULL`. If it were instead set to TRUE the function would query the meta information to guess its type. This seems desirable. But it seems so simple to change I wonder if the original author had a vision here that I am not seeing.  @eriqande, would you like to contribute to this decision?

**Comment by eriqande** [comment]
Hey Brian!
Great to hear form you.  I just pulled stuff down and found that there are 214 new commits since the last time I looked upstream.  Awesome!  I just tested info_types = TRUE and format_types = TRUE, too, and it seems to give the right result.  I guess that I might have been worried that a mismatch in the INFO field might cause coercion to NA when a user was not expecting it.  But I don't really recall at this point.  I have a vague recollection of freebayes calling things numeric when, in fact, they were numbers separated by commas.  But setting those to true by default would probably be a good thing, as long as the user is warned that an incompatibility in the INFO fields might munge their data.  But maybe VCF enforces these things sufficiently so that doesn't happen anyway?

**Comment by knausb** [comment]
Hi Eric! Its great to hear from you as well! There are instances when there can be comma delimited numbers in the data. But your code checks for 'Number=1' AND 'Type=Integer' OR 'Type=Float'. So only numerics where one value is expected should get converted. I'll work on the change and to update the docs. Thanks!

**Comment by knausb** [comment]
Merged to master, passed travis and local checks. Closed.
