### ISSUE TITLE
incorrect parsing of GT using vcfR::extract.gt with VCF from Tassel

### ISSUE THREAD

**Issue by thierrygosselin** [knausb/vcfR#50]
Hi Brian, congratulations again for the paper.

this might not be a bug related to vcfR, but I wanted to clear this with you before asking Tassel team.

I'm using vcfR for some functions in my packages stackr and assigner.
Jeremy Leluyer @jleluyer, recently tried stackr with a VCF made and filtered in Tassel and got an error (see below). I don't think it's following the vcf 4.0 specification, although it's says `##fileformat=VCFv4.0` in the header.

The VCF header:
```
##fileformat=VCFv4.0
##Tassel=<ID=GenotypeTable,Version=5,Description="Reference allele is not known. The major allele was used as reference allele">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=AD,Number=.,Type=Integer,Description="Allelic depths for the reference and alternate alleles in the order listed">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read Depth (only filtered reads used for calling)">
##FORMAT=<ID=GQ,Number=1,Type=Float,Description="Genotype Quality">
##FORMAT=<ID=PL,Number=.,Type=Float,Description="Normalized, Phred-scaled likelihoods for AA,AB,BB genotypes where A=ref and B=alt; not applicable if site is not biallelic">
##INFO=<ID=NS,Number=1,Type=Integer,Description="Number of Samples With Data">
##INFO=<ID=DP,Number=1,Type=Integer,Description="Total Depth">
##INFO=<ID=AF,Number=.,Type=Float,Description="Allele Frequency">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	
```

So you expect to find `GT, AD, DP, GQ, PL` in the FORMAT field and `NS, DP, AF` in the INFO field however this is not the case:

```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	IND1	IND2	IND3	IND4	IND5
0	192	TP192	A	C	.	PASS	.	GT	0/0	0/0	0/0	0/0	0/0
0	754	TP754	G	A	.	PASS	.	GT	0/0	0/0	0/0	0/0	0/0
0	848	TP848	C	A	.	PASS	.	GT	0/0	0/0	0/0	0/0	0/0
0	946	TP946	A	G	.	PASS	.	GT	0/0	0/0	0/0	0/0	0/0
0	1563	TP1563	C	A	.	PASS	.	GT	0/0	0/0	0/0	0/0	0/0
0	2438	TP2438	T	A	.	PASS	.	GT	0/0	0/0	0/0	0/0	0/0
0	2808	TP2808	A	G	.	PASS	.	GT	0/0	0/0	0/0	0/0	0/0
0	3264	TP3264	G	T	.	PASS	.	GT	0/0	0/0	0/0	0/0	0/0
0	3708	TP3708	C	T	.	PASS	.	GT	0/0	0/0	0/0	0/0	0/0
0	4616	TP4616	G	A	.	PASS	.	GT	0/0	0/0	./.	0/0	0/0
0	4617	TP4617	G	A	.	PASS	.	GT	0/0	0/0	./.	0/0	0/0
0	4635	TP4635	G	A	.	PASS	.	GT	0/0	0/0	0/0	0/0	0/0
0	4979	TP4979	T	A	.	PASS	.	GT	0/0	0/0	0/0	0/0	0/0
0	5087	TP5087	C	A	.	PASS	.	GT	0/0	0/0	0/0	0/0	0/0
0	5970	TP5970	A	C	.	PASS	.	GT	0/0	0/0	0/0	0/0	0/0
0	6000	TP6000	A	G	.	PASS	.	GT	0/0	0/0	0/0	0/0	0/0
0	6226	TP6226	A	G	.	PASS	.	GT	0/0	0/0	0/0	0/0	0/0
0	6528	TP6528	A	C	.	PASS	.	GT	0/0	0/0	0/0	0/0	0/0
0	7080	TP7080	C	A	.	PASS	.	GT	0/0	0/0	./.	0/0	0/0
0	7387	TP7387	C	T	.	PASS	.	GT	0/0	0/0	0/1	0/0	0/0
```

So you see that there is just the GT filled in. There is no problem reading the VCF in VCFTOOLS. 

**Problem:**
In vcfR the `./.` genotypes get parsed as `NA` instead of remaining `./.` like other VCF's I tried in vcfR.

**Question 1:** is this a bug in vcfR?

**Question 2:** even if they are not following VCF specifications (from 4.0 to 4.3) is this something you want to fix ?

There is potential for opening a door you might not want, as they can be a thousand way a VCF can go wrong an I've seen horrible genepop file going around... ;)

I've fix this behaviour in my package by scanning for `NA's` and replacing it back to `./.`
Cheers
Thierry

**Comment by knausb** [comment]
Hi Thierry,

If I understand you correctly you appear to have two questions. First you appear to ask about the validity of a specific VCF file. Second, you're concerned about how missing data are represented in vcfR.

Your concern about the validity of a VCF file seems to be due to a lack of congruence among acronyms found in the INFO and genotype columns and their definition in the meta portion of the file.  The [VCF specification](http://samtools.github.io/hts-specs/) v4.3 section 1.4 indicates that the meta information is optional. Section 1.6.2 indicates that no genotype information is required. So in theory one could construct a valid VCF file that has no definitions in the meta portion of the file and no genotype information either. Note that is is **recommended** that data provided in the INFO and genotype portions of the file are defined in the meta portion. The VCF specification also provides a list of 'reserved words' that are in common use and do not need to be defined in the meta portion. There is also an example VCF file in the specification that provides an example of variants that contain different information: the fifth variant includes GT:GQ:DP but no HQ even though it is defined in the meta portion. My interpretation is that this file you've provided appears to conform to the specification. This is a 'flexible' specification, which can sometimes lead to some confusion (I'm still learning). Does this make sense? Do you see something I've missed?

Your second question is about handling missing data in vcfR. The VCF specification section 1 indicates that missing data should be encoded as ".". Unlike many other languages R supports missing data and encodes it as "NA". The philosophy I've tried to use in vcfR is to work as an intermediary between VCF files and R functions. So I've decided to recode the VCF representation of missing data with R's representation of missing data whenever possible. This allows other R functions, such as is.na(), to correctly interpret this data. I've also tried to be relatively hands off in that I've tried to avoid converting data to NA until I'm sure its missing. For example, I would interpret:

"GT:GQ:DP"    "./.:.:."

As potentially meaningful because it is a delimited record. It is not until we un-delimit it that it becomes missing.

While in vcfR I try to maintain the above behaviour. I've also tried to get the data to play well with other formats. For example, if write.vcf() is used to create a VCF file, the NAs should be converted back to ".". Similarly, the vcfR2DNAbin() will convert NA to n in order to conform with the DNAbin's representation of missing data. I feel this provides R functionality to the vcfR object but plays nicely with other objects.

I'm curious as to why you would want to maintain your "./."? Is there a specific application you're interested in? Does it seem reasonable for this functionality to be included in a conversion function, such as vcfR2DNAbin()?

Does this sound reasonable? Apologies for a long response, but this seemed like a somewhat involved question.

Thank you!
Brian

**Comment by thierrygosselin** [comment]
Hi Brian, 

**VCF flexibility**
About the flexibility of what the VCF **says** in contains, with the use of `##` in the meta-information lines and what **it actually does** include with each genotype info is noted. I don't think it's a good habit, but this is clearly related to Tassel.

**How vcfR parse those VCF files**
The second question I had was more related to *how* vcfR parsed those files. More precisely, with the use of `vcfR::extract.gt`.

For `GT == "./."`

**1. vcfR + tassel VCF file:** vcfR change automatically the `./.` -> `NA`

**2. vcfR + stacks or GATK VCF files** *(with consistent meta-information and FORMAT field)* 
vcfR doesn't modify the genotype:  `./.` remains `./.` 

**Question:** Having 2 different ways of parsing the GT format field, is this normal/wanted vcfR behaviour ? I can send 2 vcf files for more concrete examples.

I personally think the second one is the correct way to proceed, leaving the VCF coding intact and free to modify after in vcfR or elsewhere.


Cheers
Thierry

**Comment by knausb** [comment]
Hi Thierry,

I think an example would be helpful.

    library(vcfR)
    packageVersion('vcfR') # 1.2.0
    data("vcfR_test")
    
    # Set gt slot to only GT
    gt <- extract.gt(vcfR_test)
    vcfR_test@gt[,'FORMAT'] <- 'GT'
    vcfR_test@gt[,-1] <- gt
    vcfR_test@gt[1,3] <- "./."`

    # Write to file and read in.
    write.vcf(vcfR_test, file = "test.vcf.gz")
    vcf <- read.vcfR(file = "test.vcf.gz")
    unlink("test.vcf.gz")
    vcf@gt

This illustrates that when the VCF file contains only a GT field and missing genotypes are encountered  they are converted to `NA`. This does not involve `extract.gt()`.

    # NA behaviour of extract.gt()
    data("vcfR_test")
    vcfR_test@gt[1,3] <- "./.:48:8:51,51"
    vcfR_test@gt
    gt <- extract.gt(vcfR_test)
    gt

This demonstrates that `extract.gt()` does not convert `./.` to `NA`. This appears to be an inconsistency that I should address.

Does this demonstrate why you're getting `NA` some of the time? If not, could you provide an example?

We appear to be of different opinions on how NAs should be handled. I prefer to convert them to `NA` and you are advocating to leave them as `./.`. I could add a parameter to both `read.vcfR()` and `extract.gt()`, such as `convertNA = TRUE`, to allow the user to control this behaviour. Would that address your concern?

Thanks again for your feedback!
Brian

**Comment by thierrygosselin** [comment]
Hi Brian, 

I confirm that it's from `read.vcfR` and not `extract.gt` that the difference is originating. I was using both one after another and just assumed. Also, the only VCF file I have with only the GT field are bad example... so didn't help here either.

As for the `NA` or the `./.` ....

`convertNA = TRUE` is a good option and provide the ability to opt in/out. For me it doesn't matter if it's by default or not, as I now control it with an upstream check. For consistency, if the genotype format is advertised as a *vcf-style* genotype coding, then `./.` is better.

Cheers,
and again, great work, very useful package!
Thierry

**Comment by knausb** [comment]
Added `convertNA `to `read.vcfR()` in 14d571d7512f496b29f642228af70a74cc00cec4. Note that this applies to both the GT and FIX regions. Added unit tests as well.

**Comment by knausb** [comment]
Added convertNA to `extract.gt()` in b0cf630149d7a8b7b67ef2c35b489e545e8e8739. Updated `allele.sep()` removal as well as a few other related side effects. Added unit tests.

I think this issue is now handled. Thank you Thierry!
Brian
