### ISSUE TITLE
Give users TRUE/FALSE option for masking Chrom objects in extract.gt()

### ISSUE THREAD

**Issue by zkamvar** [knausb/vcfR#6]
Currently, the behavior of `extract.gt()` is to simply extract the information from a vcfR or chrom object, but it will currently will take into account masking if the user explicitly supplies a logical vector of variants to mask. Since the information masking the data does live within a Chrom object, can you give the users an option to simply use the mask field in the Chrom object? 

Currently, the implementation looks like this:

```r
myChrom.gt <- extract.gt(myChrom, element = "GT", mask = myChrom@var.info$mask)
```

What I expect would look like:

```r
myChrom.gt <- extract.gt(myChrom, element = "GT", mask = TRUE)
```

internally, you can check the length of the vector and class of the object with something like:

```r
if ("Chrom" %in% class(x) && length(mask) == 1){
  ... use masking from var.info slot ...
} else {
  ... do what you normally do ...
}
```

**Comment by knausb** [comment]
This function was initially intended to work with both vcfR and Chrom objects.   Because the vcfR object has no mask defined the function need to be able to accept some sort of mask (a vector of logicals).  Note that in theory the 'FILTER' column could be used as a mask if converted to a vector of logicals.

I've added a test for the length of mask.  If of length one it is simply a logical.  If of length greater than one it is used as the mask.  If the mask length is less than the number of rows in the matrix it is recycled.

**Comment by zkamvar** [comment]
thanks!
