### ISSUE TITLE
*** caught segfault ***

### ISSUE THREAD

**Issue by mmahmoudian** [knausb/vcfR#79]
Hi,

I was accidentally feeding the "read.vcfR" function a tabix file (.tbi) and I got the segfault error. This means that the function never checks if the file is truly a VCF file and it just jumps in and tries to read it. I suggest you set a fail-safe switch in the beginning of the function to check this.

I have explained the issue in some details in the following URL:
https://www.synapse.org/#!Synapse:syn6187098/discussion/threadId=2617

But in brief, the error the code produces is:
```
 *** caught segfault ***
address (nil), cause 'unknown'
```
which points towards memory block allocation and probably in the C++ part of the package's code.

imho, this is super useful to have since VCFs often come along with vcf.tbi files and using a non-strick regular expression i finding the files can cause this confusing error.

**Comment by knausb** [comment]
Hi mmahmoudian,

You are correct that `read.vcfR()` does not attempt to check what sort of file its given. And I think you've provided a good example of why it should. However, I was unsuccessful at reproducing your report. I have a VCF file and it's tbi index that I tested this on.

```
library(vcfR)
vcf <- read.vcfR("NODE_1.vcf.gz")
Meta line 5368 read in.
All meta lines processed.
Character matrix gt created.
Character matrix gt rows: 158
Character matrix gt cols: 98
skip: 0
nrows: 158
row_num: 0

Processed variant: 158
All variants processed
```

Works as expected.

```
vcf <- read.vcfR("NODE_1.vcf.gz.tbi")
Meta line 0 read in.
All meta lines processed.
Character matrix gt created.
Character matrix gt rows: 0
Character matrix gt cols: 8
skip: 0
nrows: 0
row_num: 0

Warning: no header information was found! Data contains no sample names!
Processed variant: 0
All variants processed
```

Does not throw a segfault. I would describe this as an 'unexpected result'. When you get your segfault does it crash your R session? If so, it would be nice to have a reproducible example so I know I can catch that. If its just unexpected behaviour I should be able to address it with some tests.

Do you know what version of vcfR you are using? Could you post the results from the below command?

```
library(vcfR)
sessionInfo()
```

The current version at CRAN is 1.5.0.

The [VCF specification](http://samtools.github.io/hts-specs/) indicates tha the first line should look something like the following.

```
##fileformat=VCFv4.2
```

I can engineer a test that reads in the first line of the VCF file and tests this (excluding version number) and throws an error if it doesn't match.Do you feel that would address your issue?

Thank you!

**Comment by mmahmoudian** [comment]
Well, unfortunately I cannot give you the data to reproduce it, but I can sure provide almost everything else. I have a docker that runs a R code inside and tries to read the vcf files. So I have all version numbers you want. Regarding the question you asked about the session termination, I cannot provide you the answer since I faced this issue on a challenge platform in which we should submit our code in a dockerized form and the challenge organizers will run the docker containers themselves. This is also the reason that I cannot provide you the data, because I don't have access to it and by challenge's rules we participants have been kept blind to the data.

My docker has the following specs:

> DISTRIB_ID=Ubuntu
> DISTRIB_RELEASE=16.04
> DISTRIB_CODENAME=xenial
> DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
> NAME="Ubuntu"
> VERSION="16.04.3 LTS (Xenial Xerus)"
> ID=ubuntu
> ID_LIKE=debian
> PRETTY_NAME="Ubuntu 16.04.3 LTS"
> VERSION_ID="16.04"
> HOME_URL="http://www.ubuntu.com/"
> SUPPORT_URL="http://help.ubuntu.com/"
> BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
> VERSION_CODENAME=xenial
> UBUNTU_CODENAME=xenial

and

> R version 3.2.3 (2015-12-10)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Ubuntu 16.04.3 LTS
> 
> locale:
> [1] C
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base
> 
> other attached packages:
> [1] vcfR_1.5.0
> 
> loaded via a namespace (and not attached):
>  [1] MASS_7.3-45       magrittr_1.5      Matrix_1.2-3      parallel_3.2.3
>  [5] tools_3.2.3       mgcv_1.8-11       Rcpp_0.12.13      nlme_3.1-124
>  [9] ape_4.1           grid_3.2.3        permute_0.9-4     vegan_2.4-4
> [13] pinfsc50_1.1.0    viridisLite_0.2.0 cluster_2.0.3     lattice_0.20-33

**Comment by knausb** [comment]
Thanks for the system info! You do indeed have vcfR_1.5.0, so that's not the problem. Your R is a bit old, but I can't think of a reason that would matter. And I'm running ubutu 16.04 too.

If you're looking for a quick fix and haven't found it you can use a regex such as:

```
vcf.gz$
```

where the dollar sign indicates the end of the string.

In terms of the segfault, if I can't reproduce it on my end, then there may be little I can do. I've added the following to `read.vcfR()`.

```
  # Test that this is a VCF file.
  if(checkFile == TRUE){
    vcf <- scan(file=file, what = character(), nmax=1, sep="\n", quiet = TRUE, comment.char = "")
    if(substr(vcf,start=1, stop=17) != "##fileformat=VCFv"){
      msg <- paste("File:", file, "does not appear to be a VCF file.")
      msg <- paste(msg, "First line of file:", file)
      stop(msg)
    }
  }  
```

The message reports the file name (with path) and the first line of the file. This should hopefully catch instances where non-VCF files are passed to it. This is on the master branch at GitHub now. You can use the following to use it if you like.

```
devtools::install_github(repo="knausb/vcfR")
```

In the mean time, we're hoping to get an update of vcfR on CRAN in the near future. This code will be a part of it. Does this sound like it addresses your issue?

Thanks!

**Comment by mmahmoudian** [comment]
I asked the person who is responsible for the data to provide you the tabix file. I assume he have not done it and I understand that for you it is a fair reason to close this issue.
Thank you for being responsive.

**Comment by knausb** [comment]
Yup, I have not received an example that allows me to reproduce the reported behaviour. So there's little I can do on my end. As reported above, I've added some code to try to validate that the requested file is actually a VCF file. That does not directly address the segfault. But without an example I will not be able to tell whether this issue has to do with my code or perhaps how zlib tries to read the tabix. Which is why I've closed this. Thank you for reporting this and hopefully the code you've inspired me to add will improve vcfR.
