### ISSUE TITLE
read.vcfR crash

### ISSUE THREAD

**Issue by 2waybene** [knausb/vcfR#86]
When I tried to use the read.vcfR to read in a vcf file, it crashed R. Does anyone have the same/similar issue? I checked with Brian and Brian said "That looks like the sort of error that occurs when there's an issue with the C++ code. ". Also, Brian suggested that I upgrade my R to 3.4.2 (mine is 3.4.0). But, the manual clearly indicates "Depends R (>= 3.0.1)". Any help will be appreciated.

**Comment by knausb** [comment]
Hi Jianying,

As explained here:

https://knausb.github.io/vcfR_documentation/reporting_issue.html

What we really need here is a **minimal reproducible example**. This is the critical difference between simply reporting that something does not work versus providing information to help diagnose the problem and fix it. It is very difficult for me to determine what might be happening on your computer. If you can provide an example I can reproduce on my computer I can attempt to address the issue.

I've asked you to upgrade to the most current version of R. This is a very typical first step in diagnosing a problem. Even though vcfR depends on R >= 3.0.1 it uses other packages in various parts of the code. If any of these other packages requires R > 3.4.0 this would potentially explain your issue. Its typically very easy to upgrade so its an easy way to eliminate a potential issue.

I took another look at your screen shot and it reports only 1 meta line. While I think this may be valid, I feel it is suspicious. Are you sure you are using a valid VCF file? Is it possible that something has corrupted your file? If you could send mean example I could help with this determination.

Thanks!

**Comment by 2waybene** [comment]
Brain

Thank you very much for your further attention. I made it work by removing
all information rows.

Regards,

Jianying

**Comment by knausb** [comment]
Well, its good to know you have things up and working. But I'm a little concerned that there may be an issue with my code. I'm afraid I do not understand what you mean by 'information rows'. The current [VCF specification](http://samtools.github.io/hts-specs/VCFv4.3.pdf) describes VCF data as containing a number of 'meta' lines that are prefixed with two pound signs ('##') followed by a single header line prefixed with a single pound sign ('#') and all subsequent rows are variant records. By 'information rows' do you mean the meta lines? Because vcfR should read those just fine. Could you please elaborate?

Thanks!

**Comment by knausb** [comment]
Closed due to lack of reply.
