### ISSUE TITLE
read.vcfR caught segfault

### ISSUE THREAD

**Issue by igordot** [knausb/vcfR#96]
I was trying to parse what look like a very simple VCF and got this error:
```
> read.vcfR(my_vcf)
Scanning file to determine attributes.
File attributes:
  meta lines: 39
  header line: 40
  variant count: 11
  column count: 10
Meta line 39 read in.
All meta lines processed.
gt matrix initialized.
Character matrix gt created.
  Character matrix gt rows: 11
  Character matrix gt cols: 10
  skip: 0
  nrows: 11
  row_num: 0

 *** caught segfault ***
address 0x110, cause 'memory not mapped'

Traceback:
 1: .Call(`_vcfR_read_body_gz`, x, stats, nrows, skip, cols, convertNA,     verbose)
 2: .read_body_gz(file, stats = stats, nrows = nrows, skip = skip,     cols = cols, convertNA = as.numeric(convertNA), verbose = as.numeric(verbose))
 3: read.vcfR(lofreq_vcf)
```

I thought that maybe the file is too big or there is some weird character, so I tried shortening it and using output from different samples. That did not solve the problem.

This is the entire VCF:
```
##fileformat=VCFv4.0
##FILTER=<ID=PASS,Description="All filters passed">
##INFO=<ID=DP,Number=1,Type=Integer,Description="Raw Depth">
##INFO=<ID=AF,Number=1,Type=Float,Description="Allele Frequency">
##INFO=<ID=SB,Number=1,Type=Integer,Description="Phred-scaled strand bias at this position">
##INFO=<ID=DP4,Number=4,Type=Integer,Description="Counts for ref-forward bases, ref-reverse, alt-forward and alt-reverse bases">
##INFO=<ID=INDEL,Number=0,Type=Flag,Description="Indicates that the variant is an INDEL.">
##INFO=<ID=CONSVAR,Number=0,Type=Flag,Description="Indicates that the variant is a consensus variant (as opposed to a low frequency variant).">
##INFO=<ID=HRUN,Number=1,Type=Integer,Description="Homopolymer length to the right of report indel position">
##FILTER=<ID=min_snvqual_82,Description="Minimum SNV Quality (Phred) 82">
##FILTER=<ID=min_indelqual_54,Description="Minimum Indel Quality (Phred) 54">
##FILTER=<ID=min_dp_10,Description="Minimum Coverage 10">
##FILTER=<ID=sb_fdr,Description="Strand-Bias Multiple Testing Correction: fdr corr. pvalue > 0.001000">
##FILTER=<ID=min_snvqual_96,Description="Minimum SNV Quality (Phred) 96">
##FILTER=<ID=min_indelqual_67,Description="Minimum Indel Quality (Phred) 67">
##contig=<ID=chr1>
##contig=<ID=chr2>
##contig=<ID=chr3>
##contig=<ID=chr4>
##contig=<ID=chr5>
##contig=<ID=chr6>
##contig=<ID=chr7>
##contig=<ID=chr8>
##contig=<ID=chr9>
##contig=<ID=chr10>
##contig=<ID=chr11>
##contig=<ID=chr12>
##contig=<ID=chr13>
##contig=<ID=chr14>
##contig=<ID=chr15>
##contig=<ID=chr16>
##contig=<ID=chr17>
##contig=<ID=chr18>
##contig=<ID=chr19>
##contig=<ID=chr20>
##contig=<ID=chr21>
##contig=<ID=chr22>
##contig=<ID=chrX>
##contig=<ID=chrY>
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	C-WT
chr1	877831	.	T	C	4820	PASS	DP=156;AF=0.99359;SB=0;DP4=0,0,102,53
chr1	879676	.	G	A	4767	PASS	DP=146;AF=1;SB=0;DP4=0,0,46,100
chr1	879687	.	T	C	4174	PASS	DP=133;AF=1;SB=0;DP4=0,0,44,89
chr1	881627	.	G	A	1465	PASS	DP=134;AF=0.447761;SB=5;DP4=46,27,32,28
chr1	887801	.	A	G	4091	PASS	DP=128;AF=1;SB=0;DP4=0,0,75,53
chr1	888639	.	T	C	2304	PASS	DP=73;AF=1;SB=0;DP4=0,0,33,40
chr1	888659	.	T	C	1903	PASS	DP=60;AF=1;SB=0;DP4=0,0,26,34
chr1	889158	.	G	C	2016	PASS	DP=65;AF=1;SB=0;DP4=0,0,49,16
chr1	889159	.	A	C	2136	PASS	DP=65;AF=1;SB=0;DP4=0,0,49,16
chr1	896271	.	C	T	2223	PASS	DP=159;AF=0.553459;SB=11;DP4=31,40,26,62
chr1	897325	.	G	C	6942	PASS	DP=220;AF=1;SB=0;DP4=0,0,78,142
```

Is the problem due to the missing FORMAT and SAMPLE fields?

**Comment by knausb** [comment]
I think the issue is your file. The 'gt' portion of a VCF file (the FORMAT column and subsequent columns containing sample data) are optional. Your file has 'FORMAT' and 'C-WT' in the header (line beginning with '#CHROM') but the body of your file does not include this information. If you delete 'FORMAT' and 'C-WT' you should be able to read this in.

That was the short answer. The longer answer is that situation brings down the entire R session, which is undesirable. I'll take a look into it. But the issue is in the C++ code, so it may take me a bit.

Thanks!
Brian

**Comment by igordot** [comment]
Thank you for clarifying. The FORMAT and sample columns were added for compatibility with other tools. Apparently, it seems to break vcfR.

Hopefully this can be handled without bringing down the entire R session.

**Comment by knausb** [comment]
You've stated that you've added the FORMAT and sample columns for compatibility with other tools. I'm not convinced that this is a good idea. [The VCF specification v4.3](http://samtools.github.io/hts-specs/) indicates in section 1.5 that **IF** genotype data is present these will be followed by the FORMAT header and an arbitrary number of sample IDs. My interpretation of this is that your file is not following the VCF specification. Do you have a different interpretation? Could you give me some examples of tools that require this? Thanks!

**Comment by igordot** [comment]
I agree it's not a good idea. I forget what tools caused problems without my custom modification.

Since I found this problem, I switched to this script from LoFreq: https://github.com/CSB5/lofreq/blob/master/src/tools/scripts/lofreq2_add_fake_gt.py
It seems to be adding FORMAT and sample fields in a more in a more appropriate way.

**Comment by knausb** [comment]
Here's what I think is happening. When we read in a file we do not know how much data is in it. So one strategy would be to grow our data structure as we read in more data. This usually comes with a performance cost. To avoid this I use a hidden function to scan the VCF file in order to determine how many meta lines there are, which line has the header, and how many variants there are. Once we have this information we can initialize our data structure once without growing it and then populate it. Below the meta lines the VCF data is tabular, so we can read it into a matrix. In order to initialize this we need to know how many rows and columns we need. The rows come from the number of variants while the columns I've tried to get from either the number of elements in the header line or the last line of the file. Because you have a different number of elements in your header line than the last line it causes problems. When I tried to read in your file it reported that it detected 8 columns (this is different from what you report above). This means we initialized a matrix with 8 columns. When we try to assign column names to columns 9 and 10, that don't exist, we're attempting to access unallocated memory and we generate a segfault. Note that this is on the C++ side of operations.

In order to address this I've changed the behaviour of the file scanning function to include both the number of elements in the header file and the number of elements in the last line. These are initialized with zero. We then check if both are greater than zero and if so check whether they are identical. I think this is a good idea because it not only addresses the posted issue, but if a variant caller crashes before finishing it may have an incomplete final line. This may help a user diagnose this situation. The behaviour is now as follows.

```
> vcf <- read.vcfR('lofreq_vcf.vcf')
Scanning file to determine attributes.
Error in read.vcfR("lofreq_vcf.vcf") : 
  Your file appears to have 10 header elements and 8 columns in the body. This should never happen!
```

This change would not help the user use the posted file, but instead generates an error. While writing this there was another post indicating they changed their strategy to use a different method to add GT info. I currently do not read python, but I think what this script is doing is not only adding the header for a fake GT, but populating missing genotypes ('.') below this header information. See line 138. This seems like a better way to go about things. Can we agree on that? Thanks!

This change is now in the master branch and can be installed as follows.

```
devtools::install_github(repo="knausb/vcfR")
```

Note that you will need a compiler to install this. Or you can wait until our next CRAN release.

**Comment by igordot** [comment]
Yes, the script populates the missing genotypes. If I use the resulting VCF with fake GT, it is processed fine by vcfR. It's definitely better than what I was doing for several reasons.

Thank you for the fix. It's great that it will also check an incomplete VCF.
