### ISSUE TITLE
read.vcfR RStudio crash

### ISSUE THREAD

**Issue by mxrcx** [knausb/vcfR#99]
Hi, my problem is that Rstudio crashes when I try to read a vcf file and want to execute those commands:
(I think issue #86 is similar to that)

require("vcfR")
vcf <- read.vcfR("vcf_input.vcf")

################ OUTPUT################################

> require("vcfR")
Lade nötiges Paket: vcfR

   *****       ***   vcfR   ***       *****
   This is vcfR 1.7.0 
     browseVignettes('vcfR') # Documentation
     citation('vcfR') # Citation
   *****       *****      *****       *****

>   vcf <- read.vcfR("vcf_input.vcf")
Scanning file to determine attributes.
File attributes:
  meta lines: 4
  header line: 5
  variant count: 33
  column count: 26
Meta line 4 read in.
All meta lines processed.
gt matrix initialized.
Character matrix gt created.
  Character matrix gt rows: 33
  Character matrix gt cols: 26
  skip: 0
  nrows: 33
  row_num: 0

At this point RStudio says RSession aborted and I have to start a new session.

My vcf file:
![vcf_image](https://user-images.githubusercontent.com/26004999/37955318-914df800-31a8-11e8-9b83-5aebeabb7dde.png)

**Comment by knausb** [comment]
Hi @mxrcx,

Thanks for your post! Bringing down Rstudio is indeed a problem and we can probably address this. Because you have posted a graphic of your file there's little I can do to troubleshoot this. If you're comfortable posting the file, or directly e-mailing it to me, it would provide me with a minimal reproducible example that would help me troubleshoot the issue.

One thing I see is that the output from `vcfR::read.vcfR()` is reporting that your file only has 4 meta lines (lines that begin with '##'). However, your file seems to have many more than 4. This information is used to initialize containers for your data. If you initialize a vector that was 4 elements long and you try to add more than four elements to it you will try to access memory that was not allocated causing a segfault (this is happening on the C++ side which is faster than R, but less forgiving). Is it possible that you have a carriage return issue? Has this file been on a Windows machine and a Unix one?

The output from `vcfR::read.vcfR()` also reports 33 variants and 26 gt columns. This is more than your file appears to have. But I'm going to guess you've truncated the file to fit it into a screenshot? Again, if you could post the actual file it would help me troubleshoot this on my end.

You also might want to check that your header line (beginning with '#CHROM' has the same number of elements as the variant lines have. That was a problem #96 which we've addressed on the GitHub version of vcfR but have not submitted to CRAN yet.

You also have no INFO data in the body of the file while you have INFO fields defined in the meta region. Has this file been post-process or otherwise manipulated? I don't think the INFO issue should be a deal breaker, but you have no data in your FORMAT column. This means you will not be able to parse any of your genotypes. However, they all appear to be missing genotypes. So perhaps you're not interested in those?

Thanks!
Brian

**Comment by mxrcx** [comment]
[vcf_input.zip](https://github.com/knausb/vcfR/files/1855097/vcf_input.zip)

Hey Brian, 

thanks for your quick response. This is my (until now complete) vcf file which I created with a Python script and there everything worked fine. I am working on a windows machine.

It could be a problem that I have so few variant lines I will look into that maybe that is the problem.

Thank you,

Marco

**Comment by mxrcx** [comment]
Hey Brian,

thanks for your quick response. 
I think there were some mistakes in the meta section I changed it and it works now without a session abort.

**Comment by knausb** [comment]
Hi Marco,

The first four meta lines in your file begin with ##, which I feel follows the VCF specification. The remaining lines of your meta section appear to be 'protected' with quotes. Some text editors will do this to you. This means you have meta lines that begin with "## instead of ##. I interpret this as not following the VCF specification. This is important because `vcfR::readvcfR()` identifies the meta lines and stores them in a vector. Below the meta lines the data are tabular and they're stored in a matrix. I feel that having lines begin with "## above the header is nonsensical, and this is probably what generated your error. But it sounds like you've got it sorted out. 

Thanks for posting and thanks for reporting a resolution!
Brian
